services:
  db:
    image: mysql:8.0
    container_name: "evs_db_dev"
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE=${DB_NAME}
      MYSQL_USER=${DB_USER}
      MYSQL_PASSWORD=${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: "evs_web_dev"
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./manage.py:/app/manage.py
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
    
volumes:
  mysql_data: