# Generated by Django 5.2 on 2025-04-15 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('acad_year_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('osa_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('reason_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason_type', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('violation_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('uniform_violation', models.BooleanField(default=0)),
                ('dress_code_violation', models.BooleanField(default=0)),
                ('id_violation', models.BooleanField(default=0)),
                ('id_not_claimed_violation', models.BooleanField(default=0)),
                ('osa_id', models.IntegerField()),
                ('submitted_by', models.CharField(max_length=200)),
                ('id_status', models.IntegerField(default=0)),
                ('ticket_status', models.IntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('photo_path', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_validated', models.DateTimeField(blank=True, null=True)),
                ('acad_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_by_academic_year', to='EVS.academicyear')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_by_semester', to='EVS.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EVS.student')),
            ],
        ),
        migrations.CreateModel(
            name='TicketReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EVS.reason')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EVS.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='StudentViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('community_service', models.BooleanField(default=0)),
                ('community_service_status', models.SmallIntegerField(default=0, null=True)),
                ('apology_letter', models.BooleanField(default=0)),
                ('apology_letter_status', models.SmallIntegerField(default=0, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EVS.student')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EVS.violation')),
            ],
        ),
    ]
